services:

  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: always
    environment:
      - TZ=America/Argentina/Mendoza
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./letsencrypt:/letsencrypt
      - ./traefik.log:/traefik.log

    labels:
      - traefik.http.routers.api.rule=Host(`monitor.${DOMAIN}`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_LOGIN}
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=myresolver
    networks:
      - traefik

networks:
  traefik:
    external: true